### ISSUE TITLE
400 Bad Request when trying to anonymize a playlist

### ISSUE THREAD

**Issue by smohanty92** [okanten/playlistproxy.net#1]

**Comment by okanten** [comment]
Hello, can you please provide more details? I just tested and got a successful cloning. 

Did you successfully clone other playlists in the same hour before getting a 400? 

How many tracks (roughly) are in the playlist?

**Comment by smohanty92** [comment]
Hi!

I get `POST https://api.playlistproxy.net/create-playlist 400 (Bad Request)` . Tried with and wo optional params. No dice.

I'm still having the same issue.

There's 103 songs in the playlist

**Comment by okanten** [comment]
Are you using the website to clone playlists or directly accessing the API? 

Does the API return a body at all? If so, please include it. 

Spotify URL or URI? If you don't mind, can you share the URL (or URI) you are trying to clone? 

Are you using a known VPN service and/or Tor?

**Comment by smohanty92** [comment]
I'm using the website with Spotify URLs. No VPN or Tor.

I tried w/ a smaller playlist and it did work.
