### ISSUE TITLE
API source?

### ISSUE THREAD

**Issue by mrienstra** [okanten/playlistproxy.net#2]
Hi! Nice service, thank you!

Looks like the API source isn't public, as far as I can tell.

I noticed it sometimes changes albums (might be a Spotify problem), I thought I'd skim the code to see if it looks fixable and open a PR.

Would be kind of convenient to have the option to clone the title and/or description, maybe a checkbox, selecting it disables the corresponding input (to underscore the expectation).

**Comment by okanten** [comment]
Hello! Thank you for your kind words. 

This is a spotify issue. The service copies 1:1 based on the track ID.
