### ISSUE TITLE
Site is not working on my end.

### ISSUE THREAD

**Issue by dmmygt** [okanten/playlistproxy.net#5]
Hello,
I've tried multiple end devices as well as with VPN and without VPN and obviously with multiple different playlists. The site is not working for me at all. As soon as i paste the playlist link and click anonymize.The site refreshes itself and nothing happens, link is gone. As if i opened the site for the first time. Any clue what is causing the problem? 

https://open.spotify.com/playlist/0Zarq4BVkFkZOWkmqsfrjA?si=1d3c993160e54bae here is an example playlist
https://open.spotify.com/playlist/3PFTWt8MG7JgcjTK5WD7hn?si=6c7d5bc6a7934198 here is another one as well.

Best Regards.

**Comment by ruebyi** [comment]
Same here - no Error message, just a refresh.
I tried Safari, Chrome and Firefox

**Comment by okanten** [comment]
Thank you for a detailed issue report! I suspect this is related to https://github.com/okanten/playlistproxy.net/issues/3

Taking a look asap.

**Comment by okanten** [comment]
Seems like spotify has a limit on how many playlist one account can have. I'll fix this as soon as I am able to.

**Comment by okanten** [comment]
@dmmygt @ruebyi Issue should be fixed now.
